from __future__ import annotations

from pheroos.governance._commit_state._record_views import (
    CommitLivenessInputView,
    CommitWindowStateView,
    DecisionOutcomeView,
    DecisionProgressView,
)


def build_commit_window_state_payload(
    state: CommitWindowStateView,
) -> dict[str, object]:
    return {
        "absolute_deadline_step": state.absolute_deadline_step,
        "absolute_run_deadline_step": state.absolute_run_deadline_step,
        "assurance": state.assurance,
        "authority": state.authority,
        "assessment_replay_root": state.assessment_replay_root,
        "assessment_replay_state_ref": state.assessment_replay_state_ref,
        "candidate_challenge_root": state.candidate_challenge_root,
        "candidate_evidence_root": state.candidate_evidence_root,
        "candidate_lease_root": state.candidate_lease_root,
        "chain_id": state.chain_id,
        "collective_challenge_root": state.collective_challenge_root,
        "collective_evidence_root": state.collective_evidence_root,
        "collective_lease_root": state.collective_lease_root,
        "commit_policy_root": state.commit_policy_root,
        "epoch": state.epoch,
        "initialized_at_step": state.initialized_at_step,
        "issuer_id": state.issuer_id,
        "last_assessment_reason_codes": state.last_assessment_reason_codes,
        "last_assessment_ref": state.last_assessment_ref,
        "last_assessment_status": state.last_assessment_status,
        "last_context_ref": state.last_context_ref,
        "last_evaluated_step": state.last_evaluated_step,
        "last_ready": state.last_ready,
        "leader_candidate_id": state.leader_candidate_id,
        "manifest_root": state.manifest_root,
        "membership_root": state.membership_root,
        "membership_epoch_state_root": state.membership_epoch_state_root,
        "membership_snapshot_root": state.membership_snapshot_root,
        "minimum_stability_steps": state.minimum_stability_steps,
        "ordered_assessment_refs": state.ordered_assessment_refs,
        "previous_state_fingerprint": state.previous_state_fingerprint,
        "permission_root": state.permission_root,
        "profile": state.profile,
        "provenance": state.provenance,
        "protocol_id": state.protocol_id,
        "remaining_epoch_restart_budget": state.remaining_epoch_restart_budget,
        "remaining_reset_budget": state.remaining_reset_budget,
        "reset_budget_exhausted": state.reset_budget_exhausted,
        "reset_reason": state.reset_reason,
        "revision": state.revision,
        "risk_assessment_root": state.risk_assessment_root,
        "risk_chain_state_root": state.risk_chain_state_root,
        "risk_policy_root": state.risk_policy_root,
        "run_id": state.run_id,
        "target": state.target,
        "stop_resolution_root": state.stop_resolution_root,
        "support_replay_root": state.support_replay_root,
        "support_replay_state_root": state.support_replay_state_root,
        "threshold_root": state.threshold_root,
        "trace_event_id": state.trace_event_id,
        "window_count": state.window_count,
        "window_root": state.window_root,
    }


def build_commit_liveness_input_payload(
    value: CommitLivenessInputView,
) -> dict[str, object]:
    return {
        "assessment_reason_codes": value.assessment_reason_codes,
        "assessment_ref": value.assessment_ref,
        "assessment_status": value.assessment_status,
        "assurance": value.assurance,
        "authority": value.authority,
        "blocked_reason_codes": value.blocked_reason_codes,
        "certificate_ref": value.certificate_ref,
        "candidate_challenge_root": value.candidate_challenge_root,
        "candidate_evidence_root": value.candidate_evidence_root,
        "candidate_lease_root": value.candidate_lease_root,
        "collective_challenge_root": value.collective_challenge_root,
        "collective_evidence_root": value.collective_evidence_root,
        "collective_lease_root": value.collective_lease_root,
        "commit_policy_root": value.commit_policy_root,
        "context_ref": value.context_ref,
        "current_step": value.current_step,
        "deadline_reached": value.deadline_reached,
        "epoch": value.epoch,
        "finality_reason_codes": value.finality_reason_codes,
        "finality_status": value.finality_status,
        "finality_verification_ref": value.finality_verification_ref,
        "input_id": value.input_id,
        "invalid_reason_codes": value.invalid_reason_codes,
        "issuer_id": value.issuer_id,
        "leader_candidate_id": value.leader_candidate_id,
        "leader_ready_for_stability": value.leader_ready_for_stability,
        "manifest_root": value.manifest_root,
        "membership_root": value.membership_root,
        "membership_epoch_state_root": value.membership_epoch_state_root,
        "membership_snapshot_root": value.membership_snapshot_root,
        "next_required_inputs": value.next_required_inputs,
        "profile": value.profile,
        "permission_root": value.permission_root,
        "protocol_id": value.protocol_id,
        "provenance": value.provenance,
        "replay_root": value.replay_root,
        "replay_state_ref": value.replay_state_ref,
        "risk_assessment_root": value.risk_assessment_root,
        "risk_chain_state_root": value.risk_chain_state_root,
        "risk_policy_root": value.risk_policy_root,
        "run_id": value.run_id,
        "safety_violation_reason_codes": (value.safety_violation_reason_codes),
        "target": value.target,
        "stop_resolution_root": value.stop_resolution_root,
        "support_replay_root": value.support_replay_root,
        "support_replay_state_root": value.support_replay_state_root,
        "sealed_window": value.sealed_window,
        "seal_ref": value.seal_ref,
        "sealed_at_step": value.sealed_at_step,
        "heartbeat_continuous": value.heartbeat_continuous,
        "heartbeat_sequence": value.heartbeat_sequence,
        "previous_progress_ref": value.previous_progress_ref,
        "threshold_root": value.threshold_root,
        "trace_event_id": value.trace_event_id,
        "window_state_ref": value.window_state_ref,
    }


def build_decision_progress_payload(
    progress: DecisionProgressView,
) -> dict[str, object]:
    return {
        "assurance": progress.assurance,
        "absolute_deadline_step": progress.absolute_deadline_step,
        "absolute_run_deadline_step": progress.absolute_run_deadline_step,
        "assessment_ref": progress.assessment_ref,
        "candidate_challenge_root": progress.candidate_challenge_root,
        "candidate_evidence_root": progress.candidate_evidence_root,
        "candidate_lease_root": progress.candidate_lease_root,
        "collective_challenge_root": progress.collective_challenge_root,
        "collective_evidence_root": progress.collective_evidence_root,
        "collective_lease_root": progress.collective_lease_root,
        "commit_policy_root": progress.commit_policy_root,
        "context_ref": progress.context_ref,
        "current_step": progress.current_step,
        "epoch": progress.epoch,
        "leader_candidate_id": progress.leader_candidate_id,
        "manifest_root": progress.manifest_root,
        "membership_root": progress.membership_root,
        "membership_epoch_state_root": progress.membership_epoch_state_root,
        "membership_snapshot_root": progress.membership_snapshot_root,
        "minimum_stability_steps": progress.minimum_stability_steps,
        "next_required_inputs": progress.next_required_inputs,
        "phase": progress.phase,
        "permission_root": progress.permission_root,
        "profile": progress.profile,
        "protocol_id": progress.protocol_id,
        "remaining_epoch_restart_budget": progress.remaining_epoch_restart_budget,
        "remaining_reset_budget": progress.remaining_reset_budget,
        "replay_root": progress.replay_root,
        "replay_state_ref": progress.replay_state_ref,
        "risk_assessment_root": progress.risk_assessment_root,
        "risk_chain_state_root": progress.risk_chain_state_root,
        "risk_policy_root": progress.risk_policy_root,
        "run_id": progress.run_id,
        "sealed_window": progress.sealed_window,
        "seal_ref": progress.seal_ref,
        "sealed_at_step": progress.sealed_at_step,
        "heartbeat_continuous": progress.heartbeat_continuous,
        "heartbeat_sequence": progress.heartbeat_sequence,
        "previous_progress_ref": progress.previous_progress_ref,
        "target": progress.target,
        "stop_resolution_root": progress.stop_resolution_root,
        "support_replay_root": progress.support_replay_root,
        "support_replay_state_root": progress.support_replay_state_root,
        "terminal": progress.terminal,
        "threshold_root": progress.threshold_root,
        "unmet_gates": progress.unmet_gates,
        "window_count": progress.window_count,
        "window_root": progress.window_root,
        "window_state_ref": progress.window_state_ref,
    }


def build_decision_outcome_payload(
    outcome: DecisionOutcomeView,
) -> dict[str, object]:
    return {
        "assurance": outcome.assurance,
        "absolute_deadline_step": outcome.absolute_deadline_step,
        "absolute_run_deadline_step": outcome.absolute_run_deadline_step,
        "assessment_ref": outcome.assessment_ref,
        "authoritative_commit": outcome.authoritative_commit,
        "authority_scope": outcome.authority_scope,
        "candidate_id": outcome.candidate_id,
        "candidate_challenge_root": outcome.candidate_challenge_root,
        "candidate_evidence_root": outcome.candidate_evidence_root,
        "candidate_lease_root": outcome.candidate_lease_root,
        "certificate_ref": outcome.certificate_ref,
        "collective_challenge_root": outcome.collective_challenge_root,
        "collective_evidence_root": outcome.collective_evidence_root,
        "collective_lease_root": outcome.collective_lease_root,
        "commit_policy_root": outcome.commit_policy_root,
        "context_ref": outcome.context_ref,
        "current_step": outcome.current_step,
        "delivery_eligible": outcome.delivery_eligible,
        "epistemically_committed": outcome.epistemically_committed,
        "epoch": outcome.epoch,
        "execution_eligible": outcome.execution_eligible,
        "kind": outcome.kind,
        "manifest_root": outcome.manifest_root,
        "membership_root": outcome.membership_root,
        "membership_epoch_state_root": outcome.membership_epoch_state_root,
        "membership_snapshot_root": outcome.membership_snapshot_root,
        "profile": outcome.profile,
        "permission_root": outcome.permission_root,
        "protocol_id": outcome.protocol_id,
        "publication_eligible": outcome.publication_eligible,
        "reason_codes": outcome.reason_codes,
        "replay_root": outcome.replay_root,
        "replay_state_ref": outcome.replay_state_ref,
        "risk_assessment_root": outcome.risk_assessment_root,
        "risk_chain_state_root": outcome.risk_chain_state_root,
        "risk_policy_root": outcome.risk_policy_root,
        "run_id": outcome.run_id,
        "sealed_window": outcome.sealed_window,
        "seal_ref": outcome.seal_ref,
        "sealed_at_step": outcome.sealed_at_step,
        "heartbeat_continuous": outcome.heartbeat_continuous,
        "heartbeat_sequence": outcome.heartbeat_sequence,
        "previous_progress_ref": outcome.previous_progress_ref,
        "target": outcome.target,
        "stop_resolution_root": outcome.stop_resolution_root,
        "support_replay_root": outcome.support_replay_root,
        "support_replay_state_root": outcome.support_replay_state_root,
        "terminal": outcome.terminal,
        "threshold_root": outcome.threshold_root,
        "window_root": outcome.window_root,
        "window_state_ref": outcome.window_state_ref,
    }
