"""Static, thread-safe lazy facade for the Governance public ABI."""

from importlib import import_module as _import_module
from threading import RLock as _RLock
from typing import TYPE_CHECKING, Any as _Any

from pheroos.governance._public_api import (
    COMPATIBILITY_MODULES as _COMPATIBILITY_MODULES,
    PUBLIC_API as _PUBLIC_API,
)


if TYPE_CHECKING:
    from pheroos.governance.authority_domain import AUTHORITY_LEDGER_VERSION as AUTHORITY_LEDGER_VERSION
    from pheroos.governance.permission import ActionPermission as ActionPermission
    from pheroos.governance.authority_domain import AuthorityDomain as AuthorityDomain
    from pheroos.governance.commit_state import AuthorityScope as AuthorityScope
    from pheroos.governance.authority import AuthorityLevel as AuthorityLevel
    from pheroos.governance.candidate import Candidate as Candidate
    from pheroos.governance.candidate import CandidateSet as CandidateSet
    from pheroos.governance.target import CanonicalTarget as CanonicalTarget
    from pheroos.governance.collective import CollectiveDecisionState as CollectiveDecisionState
    from pheroos.governance.collective import CollectiveDecisionStep as CollectiveDecisionStep
    from pheroos.governance.authority_domain import GovernanceCommitBatch as GovernanceCommitBatch
    from pheroos.governance.authority_domain import GovernanceCommitReceipt as GovernanceCommitReceipt
    from pheroos.governance.authority_domain import GovernanceHead as GovernanceHead
    from pheroos.governance.authority_domain import GovernanceStateStore as GovernanceStateStore
    from pheroos.governance._authority.ledger import InMemoryGovernanceStateStore as InMemoryGovernanceStateStore
    from pheroos.governance.commit_numeric import COMMIT_CANONICAL_VERSION as COMMIT_CANONICAL_VERSION
    from pheroos.governance.commit_numeric import COMMIT_WIRE_VERSION as COMMIT_WIRE_VERSION
    from pheroos.governance.commit_state import CommitAssurance as CommitAssurance
    from pheroos.governance.commit_state import CommitReplayState as CommitReplayState
    from pheroos.governance.commit_state import CommitWindowState as CommitWindowState
    from pheroos.governance.stop_signal import CommitAction as CommitAction
    from pheroos.governance.commit_state import DecisionOutcome as DecisionOutcome
    from pheroos.governance.commit_state import DecisionOutcomeKind as DecisionOutcomeKind
    from pheroos.governance.commit_state import DecisionPhase as DecisionPhase
    from pheroos.governance.commit_state import DecisionProgress as DecisionProgress
    from pheroos.governance.commit_state import ReplayNamespace as ReplayNamespace
    from pheroos.governance.commit_state import ReplayReceipt as ReplayReceipt
    from pheroos.governance.evidence import EvidenceEdge as EvidenceEdge
    from pheroos.governance.evidence import EvidenceGraph as EvidenceGraph
    from pheroos.governance.evidence import EvidenceNode as EvidenceNode
    from pheroos.governance.collective import HybridCollectiveStep as HybridCollectiveStep
    from pheroos.governance.collective import HybridReplayState as HybridReplayState
    from pheroos.governance.collective import InhibitionSignal as InhibitionSignal
    from pheroos.governance.layer_coordination import LayerCoordinationPolicy as LayerCoordinationPolicy
    from pheroos.governance.layer_coordination import LayerCoordinationState as LayerCoordinationState
    from pheroos.governance.layer_coordination import LayerPerformanceSnapshot as LayerPerformanceSnapshot
    from pheroos.governance.layer_coordination import LayerProposal as LayerProposal
    from pheroos.governance.commit_numeric import MAX_AUTHORITY_INTEGER as MAX_AUTHORITY_INTEGER
    from pheroos.governance.output import OutputAuthorizationResult as OutputAuthorizationResult
    from pheroos.governance.output import OutputContract as OutputContract
    from pheroos.governance.pheromone import PHEROMONE_EXTENSION_PREFIXES as PHEROMONE_EXTENSION_PREFIXES
    from pheroos.governance.pheromone import PHEROMONE_KIND_PROFILE_MAP_VERSION as PHEROMONE_KIND_PROFILE_MAP_VERSION
    from pheroos.governance.pheromone import PheromoneBatchResult as PheromoneBatchResult
    from pheroos.governance.pheromone import PheromoneBudgetState as PheromoneBudgetState
    from pheroos.governance.pheromone import PheromoneDiffusionPolicy as PheromoneDiffusionPolicy
    from pheroos.governance.pheromone import PheromoneEdge as PheromoneEdge
    from pheroos.governance.pheromone import PheromoneExplorationObservation as PheromoneExplorationObservation
    from pheroos.governance.pheromone_feedback import PheromoneFeedback as PheromoneFeedback
    from pheroos.protocol.models import PheromoneKindProfile as PheromoneKindProfile
    from pheroos.governance.authority_domain import PreparedGovernanceTransition as PreparedGovernanceTransition
    from pheroos.governance.pheromone import PheromoneLifecycleRecord as PheromoneLifecycleRecord
    from pheroos.governance.pheromone import PheromoneNeighborhood as PheromoneNeighborhood
    from pheroos.governance.pheromone import PheromoneNormalizationRecord as PheromoneNormalizationRecord
    from pheroos.governance.pheromone import PheromonePolicy as PheromonePolicy
    from pheroos.governance.pheromone_feedback import PheromoneReinforcementResult as PheromoneReinforcementResult
    from pheroos.governance.pheromone import PheromoneScoreResult as PheromoneScoreResult
    from pheroos.governance.pheromone import PheromoneSubject as PheromoneSubject
    from pheroos.governance.pheromone import PheromoneTrail as PheromoneTrail
    from pheroos.governance.policy_adjustment import PolicyAdjustmentBatchResult as PolicyAdjustmentBatchResult
    from pheroos.governance.policy_adjustment import PolicyAdjustmentProposal as PolicyAdjustmentProposal
    from pheroos.governance.principal import PrincipalAttestation as PrincipalAttestation
    from pheroos.governance.principal import PrincipalVerification as PrincipalVerification
    from pheroos.governance.quorum import QuorumDecision as QuorumDecision
    from pheroos.governance.quorum import QuorumSignal as QuorumSignal
    from pheroos.governance.collective import RecruitmentSignal as RecruitmentSignal
    from pheroos.governance.recovery import RecoveryTrace as RecoveryTrace
    from pheroos.governance.policy_adjustment import RunScopedPolicyOverlay as RunScopedPolicyOverlay
    from pheroos.governance.pheromone import SUPPORTED_PHEROMONE_KINDS as SUPPORTED_PHEROMONE_KINDS
    from pheroos.governance.pheromone import SUPPORTED_PHEROMONE_SUBJECT_TYPES as SUPPORTED_PHEROMONE_SUBJECT_TYPES
    from pheroos.governance.collective import ScoutReport as ScoutReport
    from pheroos.governance.signal import Signal as Signal
    from pheroos.governance.signal import SignalStatus as SignalStatus
    from pheroos.governance.signal import SignalVerification as SignalVerification
    from pheroos.governance.stop_signal import StopResolution as StopResolution
    from pheroos.governance.stop_signal import StopResolutionVerification as StopResolutionVerification
    from pheroos.governance.stop_signal import StopSignal as StopSignal
    from pheroos.governance.layer_coordination import StrategyBias as StrategyBias
    from pheroos.governance.trace import TraceEvent as TraceEvent
    from pheroos.governance.commit_numeric import WEIGHT_SCALE as WEIGHT_SCALE
    from pheroos.governance.layer_coordination import allocate_layer_weights as allocate_layer_weights
    from pheroos.governance.commit_state import advance_commit_window_state as advance_commit_window_state
    from pheroos.governance.permission import action_permission_is_authoritative as action_permission_is_authoritative
    from pheroos.governance.permission import action_permission_fingerprint as action_permission_fingerprint
    from pheroos.governance.permission import action_permission_matches as action_permission_matches
    from pheroos.governance.permission import action_permission_payload as action_permission_payload
    from pheroos.governance.policy_adjustment import apply_policy_adjustment_overlay as apply_policy_adjustment_overlay
    from pheroos.governance.authority import can_verify as can_verify
    from pheroos.governance.pheromone import canonical_pheromone_kind_profiles as canonical_pheromone_kind_profiles
    from pheroos.governance.commit_numeric import canonical_commit_payload as canonical_commit_payload
    from pheroos.governance.commit_numeric import canonical_commit_set as canonical_commit_set
    from pheroos.governance.commit_numeric import checked_add as checked_add
    from pheroos.governance.commit_numeric import checked_multiply as checked_multiply
    from pheroos.governance.commit_numeric import checked_subtract as checked_subtract
    from pheroos.governance.collective import candidate_score_lineage as candidate_score_lineage
    from pheroos.governance.pheromone import clip_pheromone_deposit_strength as clip_pheromone_deposit_strength
    from pheroos.governance.pheromone import clip_pheromone_strength as clip_pheromone_strength
    from pheroos.governance.commit_numeric import ceil_scaled_count as ceil_scaled_count
    from pheroos.governance.pheromone import collect_pheromone_source_diversity as collect_pheromone_source_diversity
    from pheroos.governance.quorum import commit_candidate as commit_candidate
    from pheroos.governance.schema import commit_schema as commit_schema
    from pheroos.governance.commit_state import commit_replay_state_fingerprint as commit_replay_state_fingerprint
    from pheroos.governance.commit_state import commit_replay_state_contains as commit_replay_state_contains
    from pheroos.governance.commit_state import commit_replay_state_is_authoritative as commit_replay_state_is_authoritative
    from pheroos.governance.commit_state import commit_replay_state_is_current as commit_replay_state_is_current
    from pheroos.governance.commit_state import commit_replay_state_matches as commit_replay_state_matches
    from pheroos.governance.commit_state import commit_replay_state_payload as commit_replay_state_payload
    from pheroos.governance.commit_state import commit_window_ready as commit_window_ready
    from pheroos.governance.commit_state import commit_window_state_fingerprint as commit_window_state_fingerprint
    from pheroos.governance.commit_state import commit_window_state_is_authoritative as commit_window_state_is_authoritative
    from pheroos.governance.commit_state import commit_window_state_payload as commit_window_state_payload
    from pheroos.governance.commit_numeric import commit_payload_fingerprint as commit_payload_fingerprint
    from pheroos.governance.pheromone import deposit_pheromone as deposit_pheromone
    from pheroos.governance.pheromone import deposit_pheromone_trails as deposit_pheromone_trails
    from pheroos.governance.pheromone import diffuse_pheromone_trails as diffuse_pheromone_trails
    from pheroos.governance.pheromone import diffuse_pheromone_trails_with_records as diffuse_pheromone_trails_with_records
    from pheroos.governance.pheromone import diffusion_policy_from_collective as diffusion_policy_from_collective
    from pheroos.governance.collective import evaluate_collective_decision as evaluate_collective_decision
    from pheroos.governance.collective import evaluate_collective_decision_step as evaluate_collective_decision_step
    from pheroos.governance.collective import evaluate_hybrid_collective_step as evaluate_hybrid_collective_step
    from pheroos.governance.collective import hybrid_collective_step_is_authoritative as hybrid_collective_step_is_authoritative
    from pheroos.governance.collective import hybrid_replay_state_is_authoritative as hybrid_replay_state_is_authoritative
    from pheroos.governance.layer_coordination import evaluate_layer_coordination as evaluate_layer_coordination
    from pheroos.governance.output import evaluate_output_authorization as evaluate_output_authorization
    from pheroos.governance.quorum import evaluate_quorum_decision as evaluate_quorum_decision
    from pheroos.governance.pheromone import evaporate_trails as evaporate_trails
    from pheroos.governance.pheromone import evaporate_trails_with_records as evaporate_trails_with_records
    from pheroos.governance.pheromone import is_extension_pheromone_value as is_extension_pheromone_value
    from pheroos.governance.permission import issue_action_permission as issue_action_permission
    from pheroos.governance.commit_state import initialize_commit_replay_state as initialize_commit_replay_state
    from pheroos.governance.commit_state import initialize_commit_window_state as initialize_commit_window_state
    from pheroos.governance.layer_coordination import layer_coordination_policy_from_collective as layer_coordination_policy_from_collective
    from pheroos.governance.layer_coordination import layer_action_effect as layer_action_effect
    from pheroos.governance.layer_coordination import materialize_layer_pheromone_proposals as materialize_layer_pheromone_proposals
    from pheroos.governance.commit_numeric import multiply_scaled as multiply_scaled
    from pheroos.governance.commit_numeric import require_authority_integer as require_authority_integer
    from pheroos.governance.layer_coordination import proposal_score_delta as proposal_score_delta
    from pheroos.governance.principal import principal_attestation_fingerprint as principal_attestation_fingerprint
    from pheroos.governance.principal import principal_attestation_payload as principal_attestation_payload
    from pheroos.governance.principal import principal_verification_fingerprint as principal_verification_fingerprint
    from pheroos.governance.principal import principal_verification_is_authoritative as principal_verification_is_authoritative
    from pheroos.governance.principal import principal_verification_matches as principal_verification_matches
    from pheroos.governance.principal import principal_verification_payload as principal_verification_payload
    from pheroos.governance.pheromone import normalize_legacy_pheromone_trail as normalize_legacy_pheromone_trail
    from pheroos.governance.pheromone import observe_pheromone_exploration as observe_pheromone_exploration
    from pheroos.governance.output import output_authorized as output_authorized
    from pheroos.governance.output import output_gate_lineage as output_gate_lineage
    from pheroos.governance.pheromone import pheromone_lineage as pheromone_lineage
    from pheroos.governance.pheromone import pheromone_policy_from_collective as pheromone_policy_from_collective
    from pheroos.governance.pheromone import pheromone_subject_id as pheromone_subject_id
    from pheroos.governance.pheromone import pheromone_subject_type as pheromone_subject_type
    from pheroos.governance.pheromone_feedback import reinforce_pheromone_trails as reinforce_pheromone_trails
    from pheroos.governance.pheromone_feedback import reinforce_pheromone_trails_with_records as reinforce_pheromone_trails_with_records
    from pheroos.governance.stop_signal import resolve_stop_signal as resolve_stop_signal
    from pheroos.governance.commit_state import record_commit_replay_receipts as record_commit_replay_receipts
    from pheroos.governance.commit_state import replay_receipt_fingerprint as replay_receipt_fingerprint
    from pheroos.governance.commit_state import replay_receipt_payload as replay_receipt_payload
    from pheroos.governance.commit_state import restart_commit_window_epoch as restart_commit_window_epoch
    from pheroos.governance.collective import replay_state_from_hybrid_step as replay_state_from_hybrid_step
    from pheroos.governance.commit_numeric import require_scaled_integer as require_scaled_integer
    from pheroos.governance.collective import score_candidates as score_candidates
    from pheroos.governance.pheromone import score_pheromone_trails as score_pheromone_trails
    from pheroos.governance.pheromone import score_pheromone_trails_result as score_pheromone_trails_result
    from pheroos.governance.pheromone import score_pheromone_trails_with_breakdown as score_pheromone_trails_with_breakdown
    from pheroos.governance.commit_state import select_terminal_outcome_kind as select_terminal_outcome_kind
    from pheroos.governance.commit_numeric import scaled_ratio as scaled_ratio
    from pheroos.governance.layer_coordination import strategy_bias_score_delta as strategy_bias_score_delta
    from pheroos.governance.stop_signal import stop_resolution_verification_is_authoritative as stop_resolution_verification_is_authoritative
    from pheroos.governance.stop_signal import stop_resolution_verification_fingerprint as stop_resolution_verification_fingerprint
    from pheroos.governance.stop_signal import stop_resolution_verification_matches as stop_resolution_verification_matches
    from pheroos.governance.stop_signal import stop_resolution_verification_payload as stop_resolution_verification_payload
    from pheroos.governance.layer_coordination import validate_layer_coordination_policy as validate_layer_coordination_policy
    from pheroos.governance.schema import validate_commit_wire_record as validate_commit_wire_record
    from pheroos.governance.layer_coordination import validate_layer_performance_snapshot as validate_layer_performance_snapshot
    from pheroos.governance.layer_coordination import validate_layer_proposal as validate_layer_proposal
    from pheroos.governance.pheromone import validate_pheromone_budget_state as validate_pheromone_budget_state
    from pheroos.governance.pheromone_feedback import validate_pheromone_feedback as validate_pheromone_feedback
    from pheroos.governance.pheromone import validate_pheromone_policy as validate_pheromone_policy
    from pheroos.governance.pheromone import validate_pheromone_topology as validate_pheromone_topology
    from pheroos.governance.pheromone import validate_pheromone_trail as validate_pheromone_trail
    from pheroos.governance.policy_adjustment import validate_policy_adjustment_proposal as validate_policy_adjustment_proposal
    from pheroos.governance.policy_adjustment import validate_policy_adjustment_proposals as validate_policy_adjustment_proposals
    from pheroos.governance.collective import validate_score_breakdown as validate_score_breakdown
    from pheroos.governance.layer_coordination import validate_strategy_bias as validate_strategy_bias
    from pheroos.governance.commit_state import decision_outcome_is_authoritative as decision_outcome_is_authoritative
    from pheroos.governance.commit_state import decision_outcome_fingerprint as decision_outcome_fingerprint
    from pheroos.governance.commit_state import decision_outcome_payload as decision_outcome_payload
    from pheroos.governance.commit_state import decision_progress_is_authoritative as decision_progress_is_authoritative
    from pheroos.governance.commit_state import decision_progress_fingerprint as decision_progress_fingerprint
    from pheroos.governance.commit_state import decision_progress_payload as decision_progress_payload
    from pheroos.governance.principal import verify_principal_attestation as verify_principal_attestation
    from pheroos.governance.signal import verify_signal_input as verify_signal_input
    from pheroos.governance.stop_signal import verify_stop_resolution as verify_stop_resolution
    from pheroos.governance.challenge import ChallengeAttestation as ChallengeAttestation
    from pheroos.governance.challenge import ChallengeCoverage as ChallengeCoverage
    from pheroos.governance.challenge import ChallengeResult as ChallengeResult
    from pheroos.governance.risk import CommitThresholdSnapshot as CommitThresholdSnapshot
    from pheroos.governance.observation import CounterevidenceDisposition as CounterevidenceDisposition
    from pheroos.governance.observation import CounterevidenceDispositionKind as CounterevidenceDispositionKind
    from pheroos.governance.evidence_binding import EVIDENCE_BINDING_VERSION as EVIDENCE_BINDING_VERSION
    from pheroos.governance.support_lease import EligiblePrincipal as EligiblePrincipal
    from pheroos.governance.support_lease import EligiblePrincipalCluster as EligiblePrincipalCluster
    from pheroos.governance.support_lease import EligiblePrincipalSnapshot as EligiblePrincipalSnapshot
    from pheroos.governance.evidence_binding import EvidenceBinding as EvidenceBinding
    from pheroos.governance.evidence_binding import EvidenceGroupContribution as EvidenceGroupContribution
    from pheroos.governance.evidence_binding import EvidenceSummary as EvidenceSummary
    from pheroos.governance.observation import ObservationAttestation as ObservationAttestation
    from pheroos.governance.observation import ObservationPolarity as ObservationPolarity
    from pheroos.governance.risk import RiskAssessment as RiskAssessment
    from pheroos.governance.risk import RiskBand as RiskBand
    from pheroos.governance.evidence_binding import SourceDomainContribution as SourceDomainContribution
    from pheroos.governance.support_lease import SupportEquivocationFinding as SupportEquivocationFinding
    from pheroos.governance.support_lease import SupportLease as SupportLease
    from pheroos.governance.support_lease import SupportLeaseEvaluation as SupportLeaseEvaluation
    from pheroos.governance.support_lease import SupportLeaseExpiration as SupportLeaseExpiration
    from pheroos.governance.support_lease import SupportLeaseProposal as SupportLeaseProposal
    from pheroos.governance.support_lease import SupportLeaseRevocation as SupportLeaseRevocation
    from pheroos.governance.support_lease import SupportLeaseStatus as SupportLeaseStatus
    from pheroos.governance.support_lease import SupportLeaseSwitch as SupportLeaseSwitch
    from pheroos.governance.challenge import VerifiedChallenge as VerifiedChallenge
    from pheroos.governance.observation import VerifiedObservation as VerifiedObservation
    from pheroos.governance.evidence_binding import bind_evidence as bind_evidence
    from pheroos.governance.challenge import challenge_attestation_fingerprint as challenge_attestation_fingerprint
    from pheroos.governance.challenge import challenge_attestation_payload as challenge_attestation_payload
    from pheroos.governance.challenge import challenge_coverage_fingerprint as challenge_coverage_fingerprint
    from pheroos.governance.challenge import challenge_coverage_payload as challenge_coverage_payload
    from pheroos.governance.risk import commit_threshold_snapshot_fingerprint as commit_threshold_snapshot_fingerprint
    from pheroos.governance.risk import commit_threshold_snapshot_is_authoritative as commit_threshold_snapshot_is_authoritative
    from pheroos.governance.risk import commit_threshold_snapshot_matches as commit_threshold_snapshot_matches
    from pheroos.governance.risk import commit_threshold_snapshot_payload as commit_threshold_snapshot_payload
    from pheroos.governance.risk import commit_threshold_transition_requires_reset as commit_threshold_transition_requires_reset
    from pheroos.governance.observation import counterevidence_disposition_fingerprint as counterevidence_disposition_fingerprint
    from pheroos.governance.observation import counterevidence_disposition_is_authoritative as counterevidence_disposition_is_authoritative
    from pheroos.governance.observation import counterevidence_disposition_matches as counterevidence_disposition_matches
    from pheroos.governance.observation import counterevidence_disposition_payload as counterevidence_disposition_payload
    from pheroos.governance.observation import counterevidence_is_material_critical as counterevidence_is_material_critical
    from pheroos.governance.support_lease import eligible_principal_snapshot_fingerprint as eligible_principal_snapshot_fingerprint
    from pheroos.governance.support_lease import eligible_principal_snapshot_is_authoritative as eligible_principal_snapshot_is_authoritative
    from pheroos.governance.support_lease import eligible_principal_snapshot_matches as eligible_principal_snapshot_matches
    from pheroos.governance.support_lease import eligible_principal_snapshot_payload as eligible_principal_snapshot_payload
    from pheroos.governance.evidence_binding import evidence_binding_fingerprint as evidence_binding_fingerprint
    from pheroos.governance.evidence_binding import evidence_binding_is_authoritative as evidence_binding_is_authoritative
    from pheroos.governance.evidence_binding import evidence_binding_matches as evidence_binding_matches
    from pheroos.governance.evidence_binding import evidence_binding_payload as evidence_binding_payload
    from pheroos.governance.evidence_binding import evidence_summary_fingerprint as evidence_summary_fingerprint
    from pheroos.governance.evidence_binding import evidence_summary_payload as evidence_summary_payload
    from pheroos.governance.challenge import evaluate_challenge_coverage as evaluate_challenge_coverage
    from pheroos.governance.evidence_binding import evaluate_evidence_binding as evaluate_evidence_binding
    from pheroos.governance.support_lease import evaluate_support_leases as evaluate_support_leases
    from pheroos.governance.support_lease import expire_support_lease as expire_support_lease
    from pheroos.governance.risk import issue_commit_threshold_snapshot as issue_commit_threshold_snapshot
    from pheroos.governance.observation import issue_counterevidence_disposition as issue_counterevidence_disposition
    from pheroos.governance.support_lease import issue_eligible_principal_snapshot as issue_eligible_principal_snapshot
    from pheroos.governance.risk import issue_risk_assessment as issue_risk_assessment
    from pheroos.governance.support_lease import issue_support_lease as issue_support_lease
    from pheroos.governance.observation import observation_attestation_fingerprint as observation_attestation_fingerprint
    from pheroos.governance.observation import observation_attestation_payload as observation_attestation_payload
    from pheroos.governance.observation import observation_weight_ppm as observation_weight_ppm
    from pheroos.governance.evidence_binding import rebuild_evidence_binding_roots as rebuild_evidence_binding_roots
    from pheroos.governance.support_lease import revoke_support_lease as revoke_support_lease
    from pheroos.governance.risk import risk_assessment_fingerprint as risk_assessment_fingerprint
    from pheroos.governance.risk import risk_assessment_is_authoritative as risk_assessment_is_authoritative
    from pheroos.governance.risk import risk_assessment_matches as risk_assessment_matches
    from pheroos.governance.risk import risk_assessment_payload as risk_assessment_payload
    from pheroos.governance.risk import risk_policy_root as risk_policy_root
    from pheroos.governance.risk import risk_transition_is_monotonic as risk_transition_is_monotonic
    from pheroos.governance.support_lease import support_lease_fingerprint as support_lease_fingerprint
    from pheroos.governance.support_lease import support_lease_is_authoritative as support_lease_is_authoritative
    from pheroos.governance.support_lease import support_lease_payload as support_lease_payload
    from pheroos.governance.support_lease import support_lease_proposal_fingerprint as support_lease_proposal_fingerprint
    from pheroos.governance.support_lease import support_lease_proposal_payload as support_lease_proposal_payload
    from pheroos.governance.support_lease import support_lease_revocation_fingerprint as support_lease_revocation_fingerprint
    from pheroos.governance.support_lease import support_lease_revocation_is_authoritative as support_lease_revocation_is_authoritative
    from pheroos.governance.support_lease import support_lease_revocation_matches as support_lease_revocation_matches
    from pheroos.governance.support_lease import support_lease_revocation_payload as support_lease_revocation_payload
    from pheroos.governance.support_lease import support_lease_status as support_lease_status
    from pheroos.governance.support_lease import switch_support_lease as switch_support_lease
    from pheroos.governance.challenge import verified_challenge_fingerprint as verified_challenge_fingerprint
    from pheroos.governance.challenge import verified_challenge_is_authoritative as verified_challenge_is_authoritative
    from pheroos.governance.challenge import verified_challenge_matches as verified_challenge_matches
    from pheroos.governance.challenge import verified_challenge_payload as verified_challenge_payload
    from pheroos.governance.observation import verified_observation_fingerprint as verified_observation_fingerprint
    from pheroos.governance.observation import verified_observation_is_authoritative as verified_observation_is_authoritative
    from pheroos.governance.observation import verified_observation_matches as verified_observation_matches
    from pheroos.governance.observation import verified_observation_payload as verified_observation_payload
    from pheroos.governance.challenge import verify_challenge_attestation as verify_challenge_attestation
    from pheroos.governance.observation import verify_observation_attestation as verify_observation_attestation
    from pheroos.governance.attention import ATTENTION_AUTHORITY_SCOPE as ATTENTION_AUTHORITY_SCOPE
    from pheroos.governance.attention import ATTENTION_CHANNEL as ATTENTION_CHANNEL
    from pheroos.governance.certificate import CERTIFICATE_HASH_ALGORITHM as CERTIFICATE_HASH_ALGORITHM
    from pheroos.governance.hybrid_commit import COMMIT_AUTHORITY_SOURCE as COMMIT_AUTHORITY_SOURCE
    from pheroos.governance.certificate import EVIDENCE_COMMIT_CERTIFICATE_DISCRIMINATOR as EVIDENCE_COMMIT_CERTIFICATE_DISCRIMINATOR
    from pheroos.governance.certificate import EVIDENCE_COMMIT_CERTIFICATE_VERSION as EVIDENCE_COMMIT_CERTIFICATE_VERSION
    from pheroos.governance.attention import HYBRID_ATTENTION_PROFILE as HYBRID_ATTENTION_PROFILE
    from pheroos.governance.hybrid_commit import HYBRID_COMMIT_BINDING_PROFILE as HYBRID_COMMIT_BINDING_PROFILE
    from pheroos.governance.hybrid_commit import HYBRID_COMMIT_EVALUATION_DIAGNOSTIC_VERSION as HYBRID_COMMIT_EVALUATION_DIAGNOSTIC_VERSION
    from pheroos.governance.hybrid_commit import HYBRID_COMMIT_EVALUATION_REQUEST_VERSION as HYBRID_COMMIT_EVALUATION_REQUEST_VERSION
    from pheroos.governance.hybrid_commit import HYBRID_COMMIT_EVALUATION_VERSION as HYBRID_COMMIT_EVALUATION_VERSION
    from pheroos.governance.certificate import LOCAL_COMMIT_RECEIPT_DISCRIMINATOR as LOCAL_COMMIT_RECEIPT_DISCRIMINATOR
    from pheroos.governance.certificate import LOCAL_COMMIT_RECEIPT_VERSION as LOCAL_COMMIT_RECEIPT_VERSION
    from pheroos.governance.certificate import OUTCOME_CERTIFICATE_DISCRIMINATOR as OUTCOME_CERTIFICATE_DISCRIMINATOR
    from pheroos.governance.certificate import OUTCOME_CERTIFICATE_VERSION as OUTCOME_CERTIFICATE_VERSION
    from pheroos.governance.attention import AttentionBreakdown as AttentionBreakdown
    from pheroos.governance.attention import AttentionCandidatePriority as AttentionCandidatePriority
    from pheroos.governance.attention import AttentionReopenEligibility as AttentionReopenEligibility
    from pheroos.governance.attention import AttentionSubjectPriority as AttentionSubjectPriority
    from pheroos.governance.commit import CandidateClaimBinding as CandidateClaimBinding
    from pheroos.governance.commit import CandidateCommitInput as CandidateCommitInput
    from pheroos.governance.commit import CandidateCommitMetrics as CandidateCommitMetrics
    from pheroos.governance.commit import CommitAssessment as CommitAssessment
    from pheroos.governance.commit import CommitAssessmentStatus as CommitAssessmentStatus
    from pheroos.governance.commit import CommitEvaluationContext as CommitEvaluationContext
    from pheroos.governance.commit import CommitEvaluationError as CommitEvaluationError
    from pheroos.governance.commit import CommitEvaluationFailureKind as CommitEvaluationFailureKind
    from pheroos.governance.commit_state import CommitFinalityStatus as CommitFinalityStatus
    from pheroos.governance.commit_state import CommitFinalityVerification as CommitFinalityVerification
    from pheroos.governance.commit_state import CommitLivenessInput as CommitLivenessInput
    from pheroos.governance.output import CommitOutputAction as CommitOutputAction
    from pheroos.governance.output import CommitOutputAuthorization as CommitOutputAuthorization
    from pheroos.governance.commit import CommitReasonCode as CommitReasonCode
    from pheroos.governance.commit_state import CommitWindowSeal as CommitWindowSeal
    from pheroos.governance.support_lease import EligibleMembershipEpochState as EligibleMembershipEpochState
    from pheroos.governance.certificate import EvidenceCommitCertificate as EvidenceCommitCertificate
    from pheroos.governance.attention import ExplorationDirective as ExplorationDirective
    from pheroos.governance.hybrid_commit import HybridCommitAttentionStatus as HybridCommitAttentionStatus
    from pheroos.governance.hybrid_commit import HybridCommitDiagnostic as HybridCommitDiagnostic
    from pheroos.governance.hybrid_commit import HybridCommitDiagnosticSeverity as HybridCommitDiagnosticSeverity
    from pheroos.governance.hybrid_commit import HybridCommitEvaluation as HybridCommitEvaluation
    from pheroos.governance.hybrid_commit import HybridCommitEvaluationRequest as HybridCommitEvaluationRequest
    from pheroos.governance.hybrid_commit import HybridCommitEvaluationStatus as HybridCommitEvaluationStatus
    from pheroos.governance.hybrid_commit import HybridCommitStep as HybridCommitStep
    from pheroos.governance.certificate import LocalCommitReceipt as LocalCommitReceipt
    from pheroos.governance.certificate import OutcomeCertificate as OutcomeCertificate
    from pheroos.governance.risk import RiskAssessmentChainState as RiskAssessmentChainState
    from pheroos.governance.support_lease import SupportLeaseReplayReceipt as SupportLeaseReplayReceipt
    from pheroos.governance.support_lease import SupportLeaseReplayState as SupportLeaseReplayState
    from pheroos.governance.commit import assess_optimal_commit as assess_optimal_commit
    from pheroos.governance.attention import attention_breakdown_fingerprint as attention_breakdown_fingerprint
    from pheroos.governance.attention import attention_breakdown_is_authoritative as attention_breakdown_is_authoritative
    from pheroos.governance.attention import attention_breakdown_payload as attention_breakdown_payload
    from pheroos.governance.output import authorize_terminal_execution as authorize_terminal_execution
    from pheroos.governance.output import authorize_terminal_publication as authorize_terminal_publication
    from pheroos.governance.hybrid_commit import bind_hybrid_commit_channels as bind_hybrid_commit_channels
    from pheroos.governance.commit import build_commit_replay_receipts as build_commit_replay_receipts
    from pheroos.governance.commit import candidate_commit_metrics_fingerprint as candidate_commit_metrics_fingerprint
    from pheroos.governance.commit import candidate_commit_metrics_payload as candidate_commit_metrics_payload
    from pheroos.governance.commit import commit_assessment_fingerprint as commit_assessment_fingerprint
    from pheroos.governance.commit import commit_assessment_is_authoritative as commit_assessment_is_authoritative
    from pheroos.governance.commit import commit_assessment_payload as commit_assessment_payload
    from pheroos.governance.commit import commit_evaluation_context_fingerprint as commit_evaluation_context_fingerprint
    from pheroos.governance.commit import commit_evaluation_context_is_authoritative as commit_evaluation_context_is_authoritative
    from pheroos.governance.commit import commit_evaluation_context_payload as commit_evaluation_context_payload
    from pheroos.governance.commit_state import commit_finality_verification_fingerprint as commit_finality_verification_fingerprint
    from pheroos.governance.commit_state import commit_finality_verification_is_authoritative as commit_finality_verification_is_authoritative
    from pheroos.governance.commit_state import commit_finality_verification_payload as commit_finality_verification_payload
    from pheroos.governance.commit_state import commit_liveness_input_fingerprint as commit_liveness_input_fingerprint
    from pheroos.governance.commit_state import commit_liveness_input_is_authoritative as commit_liveness_input_is_authoritative
    from pheroos.governance.commit_state import commit_liveness_input_payload as commit_liveness_input_payload
    from pheroos.governance.output import commit_output_authorization_fingerprint as commit_output_authorization_fingerprint
    from pheroos.governance.output import commit_output_authorization_is_authoritative as commit_output_authorization_is_authoritative
    from pheroos.governance.output import commit_output_authorization_payload as commit_output_authorization_payload
    from pheroos.governance.commit_state import commit_window_seal_fingerprint as commit_window_seal_fingerprint
    from pheroos.governance.commit_state import commit_window_seal_for_state as commit_window_seal_for_state
    from pheroos.governance.commit_state import commit_window_seal_is_authoritative as commit_window_seal_is_authoritative
    from pheroos.governance.commit_state import commit_window_seal_is_current as commit_window_seal_is_current
    from pheroos.governance.commit_state import commit_window_seal_matches_receipt as commit_window_seal_matches_receipt
    from pheroos.governance.commit_state import commit_window_seal_payload as commit_window_seal_payload
    from pheroos.governance.commit_state import commit_window_state_is_current as commit_window_state_is_current
    from pheroos.governance.output import deliver_terminal_outcome as deliver_terminal_outcome
    from pheroos.governance.attention import derive_attention_breakdown as derive_attention_breakdown
    from pheroos.governance.attention import derive_exploration_directive as derive_exploration_directive
    from pheroos.governance.support_lease import eligible_membership_epoch_state_fingerprint as eligible_membership_epoch_state_fingerprint
    from pheroos.governance.support_lease import eligible_membership_epoch_state_is_authoritative as eligible_membership_epoch_state_is_authoritative
    from pheroos.governance.support_lease import eligible_membership_epoch_state_is_current as eligible_membership_epoch_state_is_current
    from pheroos.governance.support_lease import eligible_membership_epoch_state_payload as eligible_membership_epoch_state_payload
    from pheroos.governance.certificate import evidence_commit_certificate_body_root as evidence_commit_certificate_body_root
    from pheroos.governance.certificate import evidence_commit_certificate_fingerprint as evidence_commit_certificate_fingerprint
    from pheroos.governance.certificate import evidence_commit_certificate_from_payload as evidence_commit_certificate_from_payload
    from pheroos.governance.certificate import evidence_commit_certificate_payload as evidence_commit_certificate_payload
    from pheroos.governance.attention import evaluate_hybrid_attention_step as evaluate_hybrid_attention_step
    from pheroos.governance.hybrid_commit import evaluate_hybrid_commit_evaluation as evaluate_hybrid_commit_evaluation
    from pheroos.governance.hybrid_commit import evaluate_hybrid_commit_step as evaluate_hybrid_commit_step
    from pheroos.governance.attention import exploration_directive_fingerprint as exploration_directive_fingerprint
    from pheroos.governance.attention import exploration_directive_is_authoritative as exploration_directive_is_authoritative
    from pheroos.governance.attention import exploration_directive_payload as exploration_directive_payload
    from pheroos.governance.hybrid_commit import hybrid_attention_projection as hybrid_attention_projection
    from pheroos.governance.hybrid_commit import hybrid_commit_diagnostic_payload as hybrid_commit_diagnostic_payload
    from pheroos.governance.hybrid_commit import hybrid_commit_evaluation_fingerprint as hybrid_commit_evaluation_fingerprint
    from pheroos.governance.hybrid_commit import hybrid_commit_evaluation_is_authoritative as hybrid_commit_evaluation_is_authoritative
    from pheroos.governance.hybrid_commit import hybrid_commit_evaluation_payload as hybrid_commit_evaluation_payload
    from pheroos.governance.hybrid_commit import hybrid_commit_evaluation_request_fingerprint as hybrid_commit_evaluation_request_fingerprint
    from pheroos.governance.hybrid_commit import hybrid_commit_evaluation_request_payload as hybrid_commit_evaluation_request_payload
    from pheroos.governance.hybrid_commit import hybrid_commit_step_fingerprint as hybrid_commit_step_fingerprint
    from pheroos.governance.hybrid_commit import hybrid_commit_step_is_authoritative as hybrid_commit_step_is_authoritative
    from pheroos.governance.hybrid_commit import hybrid_commit_step_payload as hybrid_commit_step_payload
    from pheroos.governance.hybrid_commit import hybrid_commit_truth_projection as hybrid_commit_truth_projection
    from pheroos.governance.risk import initialize_risk_assessment_chain as initialize_risk_assessment_chain
    from pheroos.governance.support_lease import initialize_support_lease_replay_state as initialize_support_lease_replay_state
    from pheroos.governance.commit import issue_commit_evaluation_context as issue_commit_evaluation_context
    from pheroos.governance.commit_state import issue_commit_liveness_input as issue_commit_liveness_input
    from pheroos.governance.certificate import issue_evidence_commit_certificate as issue_evidence_commit_certificate
    from pheroos.governance.certificate import issue_local_commit_receipt as issue_local_commit_receipt
    from pheroos.governance.certificate import issue_outcome_certificate as issue_outcome_certificate
    from pheroos.governance.certificate import local_commit_receipt_fingerprint as local_commit_receipt_fingerprint
    from pheroos.governance.certificate import local_commit_receipt_is_authoritative as local_commit_receipt_is_authoritative
    from pheroos.governance.certificate import local_commit_receipt_matches as local_commit_receipt_matches
    from pheroos.governance.certificate import local_commit_receipt_payload as local_commit_receipt_payload
    from pheroos.governance.certificate import outcome_certificate_body_root as outcome_certificate_body_root
    from pheroos.governance.certificate import outcome_certificate_fingerprint as outcome_certificate_fingerprint
    from pheroos.governance.certificate import outcome_certificate_from_payload as outcome_certificate_from_payload
    from pheroos.governance.certificate import outcome_certificate_is_authoritative as outcome_certificate_is_authoritative
    from pheroos.governance.certificate import outcome_certificate_payload as outcome_certificate_payload
    from pheroos.governance.certificate import output_payload_fingerprint as output_payload_fingerprint
    from pheroos.governance.commit import rebuild_commit_assessment_roots as rebuild_commit_assessment_roots
    from pheroos.governance.commit_state import reduce_commit_liveness as reduce_commit_liveness
    from pheroos.governance.commit_state import reset_commit_window_state as reset_commit_window_state
    from pheroos.governance.risk import risk_assessment_chain_state_fingerprint as risk_assessment_chain_state_fingerprint
    from pheroos.governance.risk import risk_assessment_chain_state_is_authoritative as risk_assessment_chain_state_is_authoritative
    from pheroos.governance.risk import risk_assessment_chain_state_is_current as risk_assessment_chain_state_is_current
    from pheroos.governance.risk import risk_assessment_chain_state_payload as risk_assessment_chain_state_payload
    from pheroos.governance.risk import risk_assessment_is_latest as risk_assessment_is_latest
    from pheroos.governance.support_lease import support_lease_replay_receipt_payload as support_lease_replay_receipt_payload
    from pheroos.governance.support_lease import support_lease_replay_state_fingerprint as support_lease_replay_state_fingerprint
    from pheroos.governance.support_lease import support_lease_replay_state_is_authoritative as support_lease_replay_state_is_authoritative
    from pheroos.governance.support_lease import support_lease_replay_state_is_current as support_lease_replay_state_is_current
    from pheroos.governance.support_lease import support_lease_replay_state_payload as support_lease_replay_state_payload
    from pheroos.governance.certificate import verify_evidence_commit_certificate as verify_evidence_commit_certificate
    from pheroos.governance.certificate import verify_evidence_commit_finality as verify_evidence_commit_finality
    from pheroos.governance.certificate import verify_local_commit_finality as verify_local_commit_finality
    from pheroos.governance.certificate import verify_outcome_certificate as verify_outcome_certificate
    from pheroos.governance.distributed_commit import DISTRIBUTED_COMMIT_CERTIFICATE_DISCRIMINATOR as DISTRIBUTED_COMMIT_CERTIFICATE_DISCRIMINATOR
    from pheroos.governance.distributed_commit import DISTRIBUTED_COMMIT_CERTIFICATE_VERSION as DISTRIBUTED_COMMIT_CERTIFICATE_VERSION
    from pheroos.governance.distributed_commit import DISTRIBUTED_COMMIT_VALUE_VERSION as DISTRIBUTED_COMMIT_VALUE_VERSION
    from pheroos.governance.distributed_commit import DISTRIBUTED_FINALITY_DECISION_VERSION as DISTRIBUTED_FINALITY_DECISION_VERSION
    from pheroos.governance.distributed_commit import DISTRIBUTED_PROPOSAL_VERSION as DISTRIBUTED_PROPOSAL_VERSION
    from pheroos.governance.distributed_commit import DISTRIBUTED_STATE_VERSION as DISTRIBUTED_STATE_VERSION
    from pheroos.governance.distributed_commit import EPOCH_TRANSITION_CERTIFICATE_DISCRIMINATOR as EPOCH_TRANSITION_CERTIFICATE_DISCRIMINATOR
    from pheroos.governance.distributed_commit import EPOCH_TRANSITION_CERTIFICATE_VERSION as EPOCH_TRANSITION_CERTIFICATE_VERSION
    from pheroos.governance.distributed_commit import QUORUM_WITNESS_VERSION as QUORUM_WITNESS_VERSION
    from pheroos.governance.distributed_commit import WITNESS_VERIFICATION_VERSION as WITNESS_VERIFICATION_VERSION
    from pheroos.governance.distributed_commit import CertificateConflictFinding as CertificateConflictFinding
    from pheroos.governance.distributed_commit import DistributedCertificateStatus as DistributedCertificateStatus
    from pheroos.governance.distributed_commit import DistributedCommitCertificate as DistributedCommitCertificate
    from pheroos.governance.distributed_commit import DistributedCommitProposal as DistributedCommitProposal
    from pheroos.governance.distributed_commit import DistributedCommitState as DistributedCommitState
    from pheroos.governance.distributed_commit import DistributedFinalityDecision as DistributedFinalityDecision
    from pheroos.governance.distributed_commit import DistributedFinalityKind as DistributedFinalityKind
    from pheroos.governance.distributed_commit import EpochTransitionCertificate as EpochTransitionCertificate
    from pheroos.governance.distributed_commit import FinalCertificateRegistration as FinalCertificateRegistration
    from pheroos.governance.distributed_commit import PortableEligibleCluster as PortableEligibleCluster
    from pheroos.governance.distributed_commit import PortableEligiblePrincipal as PortableEligiblePrincipal
    from pheroos.governance.distributed_commit import PortableMembershipSnapshot as PortableMembershipSnapshot
    from pheroos.governance.distributed_commit import QuorumWitness as QuorumWitness
    from pheroos.governance.distributed_commit import WitnessEquivocationFinding as WitnessEquivocationFinding
    from pheroos.governance.distributed_commit import WitnessReplayReceipt as WitnessReplayReceipt
    from pheroos.governance.distributed_commit import WitnessVerification as WitnessVerification
    from pheroos.governance.distributed_commit import assemble_portable_distributed_commit_certificate as assemble_portable_distributed_commit_certificate
    from pheroos.governance.distributed_commit import distributed_commit_certificate_fingerprint as distributed_commit_certificate_fingerprint
    from pheroos.governance.distributed_commit import distributed_commit_certificate_from_payload as distributed_commit_certificate_from_payload
    from pheroos.governance.distributed_commit import distributed_commit_certificate_is_current_final as distributed_commit_certificate_is_current_final
    from pheroos.governance.distributed_commit import distributed_commit_certificate_payload as distributed_commit_certificate_payload
    from pheroos.governance.distributed_commit import distributed_commit_value_payload as distributed_commit_value_payload
    from pheroos.governance.distributed_commit import distributed_commit_value_root as distributed_commit_value_root
    from pheroos.governance.distributed_commit import distributed_commit_proposal_fingerprint as distributed_commit_proposal_fingerprint
    from pheroos.governance.distributed_commit import distributed_commit_proposal_from_payload as distributed_commit_proposal_from_payload
    from pheroos.governance.distributed_commit import distributed_commit_proposal_is_authoritative as distributed_commit_proposal_is_authoritative
    from pheroos.governance.distributed_commit import distributed_commit_proposal_payload as distributed_commit_proposal_payload
    from pheroos.governance.distributed_commit import distributed_commit_state_fingerprint as distributed_commit_state_fingerprint
    from pheroos.governance.distributed_commit import distributed_commit_state_from_payload as distributed_commit_state_from_payload
    from pheroos.governance.distributed_commit import distributed_commit_state_is_authoritative as distributed_commit_state_is_authoritative
    from pheroos.governance.distributed_commit import distributed_commit_state_is_current as distributed_commit_state_is_current
    from pheroos.governance.distributed_commit import distributed_commit_state_payload as distributed_commit_state_payload
    from pheroos.governance.distributed_commit import distributed_finality_decision_fingerprint as distributed_finality_decision_fingerprint
    from pheroos.governance.distributed_commit import distributed_finality_decision_from_payload as distributed_finality_decision_from_payload
    from pheroos.governance.distributed_commit import distributed_finality_decision_is_authoritative as distributed_finality_decision_is_authoritative
    from pheroos.governance.distributed_commit import distributed_finality_decision_payload as distributed_finality_decision_payload
    from pheroos.governance.distributed_commit import epoch_transition_certificate_body_root as epoch_transition_certificate_body_root
    from pheroos.governance.distributed_commit import epoch_transition_certificate_fingerprint as epoch_transition_certificate_fingerprint
    from pheroos.governance.distributed_commit import epoch_transition_certificate_from_payload as epoch_transition_certificate_from_payload
    from pheroos.governance.distributed_commit import epoch_transition_certificate_payload as epoch_transition_certificate_payload
    from pheroos.governance.distributed_commit import epoch_transition_decision_ref as epoch_transition_decision_ref
    from pheroos.governance.distributed_commit import evaluate_distributed_finality as evaluate_distributed_finality
    from pheroos.governance.distributed_commit import initialize_distributed_commit_state as initialize_distributed_commit_state
    from pheroos.governance.distributed_commit import issue_distributed_commit_certificate as issue_distributed_commit_certificate
    from pheroos.governance.distributed_commit import issue_distributed_commit_proposal as issue_distributed_commit_proposal
    from pheroos.governance.distributed_commit import issue_epoch_transition_certificate as issue_epoch_transition_certificate
    from pheroos.governance.distributed_commit import portable_membership_root as portable_membership_root
    from pheroos.governance.distributed_commit import portable_membership_snapshot_fingerprint as portable_membership_snapshot_fingerprint
    from pheroos.governance.distributed_commit import portable_membership_snapshot_from_eligible as portable_membership_snapshot_from_eligible
    from pheroos.governance.distributed_commit import portable_membership_snapshot_from_payload as portable_membership_snapshot_from_payload
    from pheroos.governance.distributed_commit import portable_membership_snapshot_payload as portable_membership_snapshot_payload
    from pheroos.governance.distributed_commit import quorum_witness_fingerprint as quorum_witness_fingerprint
    from pheroos.governance.distributed_commit import quorum_witness_from_payload as quorum_witness_from_payload
    from pheroos.governance.distributed_commit import quorum_witness_payload as quorum_witness_payload
    from pheroos.governance.distributed_commit import quorum_witness_signing_payload as quorum_witness_signing_payload
    from pheroos.governance.distributed_commit import quorum_witness_signing_root as quorum_witness_signing_root
    from pheroos.governance.distributed_commit import record_witness_verifications as record_witness_verifications
    from pheroos.governance.distributed_commit import register_distributed_commit_certificate as register_distributed_commit_certificate
    from pheroos.governance.distributed_commit import transition_distributed_commit_epoch as transition_distributed_commit_epoch
    from pheroos.governance.distributed_commit import verify_distributed_commit_certificate as verify_distributed_commit_certificate
    from pheroos.governance.distributed_commit import verify_distributed_commit_finality as verify_distributed_commit_finality
    from pheroos.governance.distributed_commit import verify_distributed_commit_proposal as verify_distributed_commit_proposal
    from pheroos.governance.distributed_commit import verify_epoch_transition_certificate as verify_epoch_transition_certificate
    from pheroos.governance.distributed_commit import verify_portable_witness_verification as verify_portable_witness_verification
    from pheroos.governance.distributed_commit import verify_quorum_witness as verify_quorum_witness
    from pheroos.governance.distributed_commit import witness_replay_receipt as witness_replay_receipt
    from pheroos.governance.distributed_commit import witness_replay_receipt_fingerprint as witness_replay_receipt_fingerprint
    from pheroos.governance.distributed_commit import witness_replay_receipt_from_payload as witness_replay_receipt_from_payload
    from pheroos.governance.distributed_commit import witness_replay_receipt_payload as witness_replay_receipt_payload
    from pheroos.governance.distributed_commit import witness_verification_fingerprint as witness_verification_fingerprint
    from pheroos.governance.distributed_commit import witness_verification_from_payload as witness_verification_from_payload
    from pheroos.governance.distributed_commit import witness_verification_is_authoritative as witness_verification_is_authoritative
    from pheroos.governance.distributed_commit import witness_verification_payload as witness_verification_payload
    from pheroos.governance.replay import challenge_replay_receipt as challenge_replay_receipt
    from pheroos.governance.replay import counterevidence_disposition_replay_receipt as counterevidence_disposition_replay_receipt
    from pheroos.governance.replay import evidence_replay_inputs_are_recorded as evidence_replay_inputs_are_recorded
    from pheroos.governance.replay import missing_evidence_replay_input_refs as missing_evidence_replay_input_refs
    from pheroos.governance.replay import observation_replay_receipt as observation_replay_receipt
    from pheroos.governance.replay import record_evidence_replay_inputs as record_evidence_replay_inputs
    from pheroos.governance.atomic_evaluation import ATOMIC_HYBRID_COMMIT_VERSION as ATOMIC_HYBRID_COMMIT_VERSION
    from pheroos.governance.atomic_evaluation import AtomicHybridCommitResult as AtomicHybridCommitResult
    from pheroos.governance.atomic_evaluation import AtomicHybridCommitStatus as AtomicHybridCommitStatus
    from pheroos.governance.atomic_evaluation import PreparedHybridCommitTransition as PreparedHybridCommitTransition
    from pheroos.governance.atomic_evaluation import commit_prepared_hybrid_transition as commit_prepared_hybrid_transition
    from pheroos.governance.atomic_evaluation import evaluate_and_commit_hybrid_step as evaluate_and_commit_hybrid_step
    from pheroos.governance.atomic_evaluation import finalize_hybrid_commit_transition as finalize_hybrid_commit_transition
    from pheroos.governance.atomic_evaluation import hybrid_commit_stream as hybrid_commit_stream
    from pheroos.governance.atomic_evaluation import prepare_hybrid_commit_transition as prepare_hybrid_commit_transition

del TYPE_CHECKING

__all__ = list(_PUBLIC_API)

_PUBLIC_API_LOCK = _RLock()


def __getattr__(name: str) -> _Any:
    target = _PUBLIC_API.get(name)
    compatibility_module = _COMPATIBILITY_MODULES.get(name)
    if target is None and compatibility_module is None:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        )
    with _PUBLIC_API_LOCK:
        if name in globals():
            return globals()[name]
        if target is not None:
            module_name, attribute = target
            value = getattr(_import_module(module_name), attribute)
        else:
            value = _import_module(compatibility_module)
        globals()[name] = value
        return value


def __dir__() -> list[str]:
    return sorted(
        set(globals()) | set(_PUBLIC_API) | set(_COMPATIBILITY_MODULES)
    )
