"""Draft public Commit Decision v2 ABI.

Portable requests, proposals, snapshots, and finality projections are data,
not authority.  Decision authority requires opaque Store-verified inputs, an
exact issuer session, and one atomic StateStore v2 commit.  When a certified
or distributed finality owner is not consumed through an opaque verified
handle, Decision still observes that owner's current head as a CAS dependency;
it never infers owner status from generic stored bytes.
"""

from pheroos.governance._commit_decision_v2 import (
    COMMIT_DECISION_ASSESSMENT_SCHEMA_V2,
    COMMIT_DECISION_CANDIDATE_PROPOSAL_SCHEMA_V2,
    COMMIT_DECISION_CANONICAL_VERSION_V2,
    COMMIT_DECISION_DEPENDENCY_SCHEMA_V2,
    COMMIT_DECISION_EVIDENCE_PROPOSAL_SCHEMA_V2,
    COMMIT_DECISION_GENESIS_HISTORY_ROOT_V2,
    COMMIT_DECISION_GENESIS_SNAPSHOT_ROOT_V2,
    COMMIT_DECISION_GENESIS_TRANSITION_ID_V2,
    COMMIT_DECISION_OUTCOME_SCHEMA_V2,
    COMMIT_DECISION_OUTPUT_PROPOSAL_SCHEMA_V2,
    COMMIT_DECISION_PROGRESS_SCHEMA_V2,
    COMMIT_DECISION_REQUEST_SCHEMA_V2,
    COMMIT_DECISION_SEAL_INCLUSION_SCHEMA_V2,
    COMMIT_DECISION_SEAL_SCHEMA_V2,
    COMMIT_DECISION_SNAPSHOT_SCHEMA_V2,
    COMMIT_DECISION_STATE_SCHEMA_V2,
    COMMIT_DECISION_WINDOW_SCHEMA_V2,
    MAX_COMMIT_DECISION_ITEMS_V2,
    MAX_COMMIT_DECISION_RESOURCE_DEPTH_V2,
    MAX_COMMIT_DECISION_RESOURCE_NODES_V2,
    MAX_COMMIT_DECISION_RESOURCE_TEXT_BYTES_V2,
    MAX_COMMIT_DECISION_SNAPSHOT_BYTES_V2,
    MAX_COMMIT_DECISION_TEXT_BYTES_V2,
    CommitAssessmentV2,
    CommitCandidateMetricsV2,
    CommitDecisionCandidateProposalV2,
    CommitDecisionCommandV2,
    CommitDecisionDependencyRoleV2,
    CommitDecisionDependencyV2,
    CommitDecisionEvidenceProposalV2,
    CommitDecisionGateStatusV2,
    CommitDecisionMutationKindV2,
    CommitDecisionOutcomeKindV2,
    CommitDecisionOutcomeV2,
    CommitDecisionOutputProposalV2,
    CommitDecisionPhaseV2,
    CommitDecisionProgressV2,
    CommitDecisionRequestV2,
    CommitDecisionSealInclusionV2,
    CommitDecisionSnapshotV2,
    CommitDecisionWindowSealV2,
    CommitDecisionWindowV2,
    VerifiedCommitDecisionSourceV2,
    VerifiedCommitDecisionStateV2,
    advance_commit_decision_v2,
    canonical_candidate_proposals_v2,
    canonical_commit_decision_dependencies_v2,
    commit_decision_dependency_set_root_v2,
    commit_decision_frozen_dependency_root_v2,
    commit_decision_history_advance_v2,
    commit_decision_state_is_current_v2,
    commit_decision_stream_ref_v2,
    commit_decision_transition_id_v2,
    open_commit_decision_authority_session_v2,
    prepare_commit_decision_initialize_v2,
    prepare_commit_decision_missing_inputs_v2,
    prepare_commit_decision_successor_v2,
    reduce_commit_decision_v2,
    rehydrate_commit_decision_state_v2,
    require_current_commit_decision_state_v2,
    verify_commit_decision_request_source_v2,
)
from pheroos.governance.commit_finality_v2 import (
    COMMIT_FINALITY_INPUT_SCHEMA_V2,
    COMMIT_FINALITY_PROJECTION_SCHEMA_V2,
    CommitFinalityOwnerV2,
    CommitFinalityProjectionV2,
    CommitFinalityStatusV2,
    VerifiedCommitFinalityInputV2,
    commit_finality_owner_genesis_snapshot_root_v2,
    commit_finality_owner_stream_ref_v2,
)


_PUBLIC_MODULE = __name__
_PUBLIC_OBJECTS = (
    CommitAssessmentV2,
    CommitCandidateMetricsV2,
    CommitDecisionCandidateProposalV2,
    CommitDecisionCommandV2,
    CommitDecisionDependencyRoleV2,
    CommitDecisionDependencyV2,
    CommitDecisionEvidenceProposalV2,
    CommitDecisionGateStatusV2,
    CommitDecisionMutationKindV2,
    CommitDecisionOutcomeKindV2,
    CommitDecisionOutcomeV2,
    CommitDecisionOutputProposalV2,
    CommitDecisionPhaseV2,
    CommitDecisionProgressV2,
    CommitDecisionRequestV2,
    CommitDecisionSealInclusionV2,
    CommitDecisionSnapshotV2,
    CommitDecisionWindowSealV2,
    CommitDecisionWindowV2,
    VerifiedCommitDecisionSourceV2,
    VerifiedCommitDecisionStateV2,
    advance_commit_decision_v2,
    canonical_candidate_proposals_v2,
    canonical_commit_decision_dependencies_v2,
    commit_decision_dependency_set_root_v2,
    commit_decision_frozen_dependency_root_v2,
    commit_decision_history_advance_v2,
    commit_decision_state_is_current_v2,
    commit_decision_stream_ref_v2,
    commit_decision_transition_id_v2,
    open_commit_decision_authority_session_v2,
    prepare_commit_decision_initialize_v2,
    prepare_commit_decision_missing_inputs_v2,
    prepare_commit_decision_successor_v2,
    reduce_commit_decision_v2,
    rehydrate_commit_decision_state_v2,
    require_current_commit_decision_state_v2,
    verify_commit_decision_request_source_v2,
)
for _item in _PUBLIC_OBJECTS:
    _item.__module__ = _PUBLIC_MODULE
del _item


__all__ = [
    "COMMIT_DECISION_ASSESSMENT_SCHEMA_V2",
    "COMMIT_DECISION_CANDIDATE_PROPOSAL_SCHEMA_V2",
    "COMMIT_DECISION_CANONICAL_VERSION_V2",
    "COMMIT_DECISION_DEPENDENCY_SCHEMA_V2",
    "COMMIT_DECISION_EVIDENCE_PROPOSAL_SCHEMA_V2",
    "COMMIT_DECISION_GENESIS_HISTORY_ROOT_V2",
    "COMMIT_DECISION_GENESIS_SNAPSHOT_ROOT_V2",
    "COMMIT_DECISION_GENESIS_TRANSITION_ID_V2",
    "COMMIT_DECISION_OUTCOME_SCHEMA_V2",
    "COMMIT_DECISION_OUTPUT_PROPOSAL_SCHEMA_V2",
    "COMMIT_DECISION_PROGRESS_SCHEMA_V2",
    "COMMIT_DECISION_REQUEST_SCHEMA_V2",
    "COMMIT_DECISION_SEAL_INCLUSION_SCHEMA_V2",
    "COMMIT_DECISION_SEAL_SCHEMA_V2",
    "COMMIT_DECISION_SNAPSHOT_SCHEMA_V2",
    "COMMIT_DECISION_STATE_SCHEMA_V2",
    "COMMIT_DECISION_WINDOW_SCHEMA_V2",
    "COMMIT_FINALITY_INPUT_SCHEMA_V2",
    "COMMIT_FINALITY_PROJECTION_SCHEMA_V2",
    "MAX_COMMIT_DECISION_ITEMS_V2",
    "MAX_COMMIT_DECISION_RESOURCE_DEPTH_V2",
    "MAX_COMMIT_DECISION_RESOURCE_NODES_V2",
    "MAX_COMMIT_DECISION_RESOURCE_TEXT_BYTES_V2",
    "MAX_COMMIT_DECISION_SNAPSHOT_BYTES_V2",
    "MAX_COMMIT_DECISION_TEXT_BYTES_V2",
    "CommitAssessmentV2",
    "CommitCandidateMetricsV2",
    "CommitDecisionCandidateProposalV2",
    "CommitDecisionCommandV2",
    "CommitDecisionDependencyRoleV2",
    "CommitDecisionDependencyV2",
    "CommitDecisionEvidenceProposalV2",
    "CommitDecisionGateStatusV2",
    "CommitDecisionMutationKindV2",
    "CommitDecisionOutcomeKindV2",
    "CommitDecisionOutcomeV2",
    "CommitDecisionOutputProposalV2",
    "CommitDecisionPhaseV2",
    "CommitDecisionProgressV2",
    "CommitDecisionRequestV2",
    "CommitDecisionSealInclusionV2",
    "CommitDecisionSnapshotV2",
    "CommitDecisionWindowSealV2",
    "CommitDecisionWindowV2",
    "CommitFinalityOwnerV2",
    "CommitFinalityProjectionV2",
    "CommitFinalityStatusV2",
    "VerifiedCommitDecisionSourceV2",
    "VerifiedCommitDecisionStateV2",
    "VerifiedCommitFinalityInputV2",
    "advance_commit_decision_v2",
    "canonical_candidate_proposals_v2",
    "canonical_commit_decision_dependencies_v2",
    "commit_decision_dependency_set_root_v2",
    "commit_decision_frozen_dependency_root_v2",
    "commit_decision_history_advance_v2",
    "commit_decision_state_is_current_v2",
    "commit_decision_stream_ref_v2",
    "commit_decision_transition_id_v2",
    "commit_finality_owner_genesis_snapshot_root_v2",
    "commit_finality_owner_stream_ref_v2",
    "open_commit_decision_authority_session_v2",
    "prepare_commit_decision_initialize_v2",
    "prepare_commit_decision_missing_inputs_v2",
    "prepare_commit_decision_successor_v2",
    "reduce_commit_decision_v2",
    "rehydrate_commit_decision_state_v2",
    "require_current_commit_decision_state_v2",
    "verify_commit_decision_request_source_v2",
]
