"""Public Draft ABI for durable Principal Verification, Membership, and Support v2.

Portable records, requests, snapshots, and evaluations carry deterministic
meaning only.  Authority is established by the exact authority session and
atomic StateStore v2 commit performed by the corresponding advance operation.
The three ledgers form one explicit dependency chain::

    PrincipalVerificationSet -> Membership -> Support

No object exported here depends on the legacy Support owner.
"""

from __future__ import annotations

from pheroos.governance._support_v2.durable_context import (
    MEMBERSHIP_POLICY_VERSION_V2,
    PRINCIPAL_VERIFICATION_POLICY_VERSION_V2,
    DurableSupportContextV2,
    durable_support_context_v2,
)
from pheroos.governance._support_v2.common import (
    MAX_SUPPORT_RESOURCE_DEPTH_V2,
    MAX_SUPPORT_RESOURCE_NODES_V2,
    MAX_SUPPORT_RESOURCE_TEXT_BYTES_V2,
    MAX_SUPPORT_TEXT_BYTES_V2,
)
from pheroos.governance._support_v2.evaluation import (
    SupportEvaluationV2,
    evaluate_support_v2,
    support_lease_status_v2,
)
from pheroos.governance._support_v2.support_evaluation_contracts import (
    SUPPORT_EVALUATION_SCHEMA_V2,
)
from pheroos.governance._support_v2.membership_contracts import (
    MAX_MEMBERSHIP_CLUSTERS_V2,
    MAX_MEMBERSHIP_PRINCIPALS_V2,
    MAX_MEMBERSHIP_SNAPSHOT_BYTES_V2,
    MEMBERSHIP_CLUSTER_SCHEMA_V2,
    MEMBERSHIP_COMMIT_REQUEST_SCHEMA_V2,
    MEMBERSHIP_GENESIS_SNAPSHOT_ROOT_V2,
    MEMBERSHIP_GENESIS_TRANSITION_ID_V2,
    MEMBERSHIP_PRINCIPAL_SCHEMA_V2,
    MEMBERSHIP_SNAPSHOT_SCHEMA_V2,
    MEMBERSHIP_STATE_SCHEMA_V2,
    MembershipClusterV2,
    MembershipCommitRequestV2,
    MembershipPrincipalV2,
    MembershipSnapshotV2,
    canonical_membership_clusters_v2,
    membership_projection_root_v2,
    membership_stream_ref_v2,
    membership_transition_id_v2,
)
from pheroos.governance._support_v2.membership_operations import (
    VerifiedMembershipStateV2,
    commit_membership_epoch_v2,
    membership_state_is_current_v2,
    open_membership_authority_session_v2,
    rehydrate_membership_state_v2,
    require_current_membership_state_v2,
)
from pheroos.governance._support_v2.membership_source import (
    VerifiedMembershipSourceV2,
    prepare_membership_commit_v2,
    verify_membership_request_source_v2,
)
from pheroos.governance._support_v2.principal_verification_contracts import (
    MAX_PRINCIPAL_VERIFICATION_SET_BYTES_V2,
    PRINCIPAL_VERIFICATION_GENESIS_SNAPSHOT_ROOT_V2,
    PRINCIPAL_VERIFICATION_GENESIS_TRANSITION_ID_V2,
    PRINCIPAL_VERIFICATION_SET_REQUEST_SCHEMA_V2,
    PRINCIPAL_VERIFICATION_SET_SNAPSHOT_SCHEMA_V2,
    PRINCIPAL_VERIFICATION_SET_STATE_SCHEMA_V2,
    PrincipalVerificationSetAdvanceRequestV2,
    PrincipalVerificationSetSnapshotV2,
    principal_verification_stream_ref_v2,
    principal_verification_transition_id_v2,
)
from pheroos.governance._support_v2.principal_verification_operations import (
    VerifiedPrincipalVerificationSetStateV2,
    advance_principal_verification_set_v2,
    open_principal_verification_authority_session_v2,
    principal_verification_set_is_current_v2,
    rehydrate_principal_verification_set_state_v2,
    require_current_principal_verification_set_v2,
)
from pheroos.governance._support_v2.principal_verification_records import (
    MAX_PRINCIPAL_VERIFICATIONS_V2,
    MAX_VERIFICATION_EVIDENCE_ROOTS_V2,
    MAX_VERIFICATION_SOURCE_TRACE_ROOTS_V2,
    PRINCIPAL_VERIFICATION_RECORD_SCHEMA_V2,
    PrincipalVerificationRecordV2,
    canonical_verification_records_v2,
)
from pheroos.governance._support_v2.principal_verification_source import (
    VerifiedPrincipalVerificationSourceV2,
    prepare_principal_verification_set_v2,
    verify_principal_verification_source_v2,
)
from pheroos.governance._support_v2.support_contracts import (
    MAX_SUPPORT_LEASES_V2,
    MAX_SUPPORT_OBSERVATIONS_V2,
    MAX_SUPPORT_REASON_CODES_V2,
    MAX_SUPPORT_SNAPSHOT_BYTES_V2,
    MAX_SUPPORT_TRACE_ROOTS_V2,
    SUPPORT_ADVANCE_REQUEST_SCHEMA_V2,
    SUPPORT_GENESIS_HISTORY_ROOT_V2,
    SUPPORT_GENESIS_SNAPSHOT_ROOT_V2,
    SUPPORT_GENESIS_TRANSITION_ID_V2,
    SUPPORT_SNAPSHOT_SCHEMA_V2,
    SUPPORT_STATE_SCHEMA_V2,
    SupportAdvanceRequestV2,
    SupportEquivocationV2,
    SupportLeaseProposalV2,
    SupportLeaseStatusV2,
    SupportLeaseV2,
    SupportMutationKindV2,
    SupportObservationV2,
    SupportRevocationV2,
    SupportSnapshotV2,
    canonical_support_leases_v2,
    canonical_support_observations_v2,
    replacement_matches_prior_v2,
    revocation_matches_lease_v2,
    support_event_lineage_v2,
    support_history_advance_v2,
    support_issued_event_lineage_v2,
    support_lease_ref_v2,
    support_mutation_delta_root_v2,
    support_revocation_ref_v2,
    support_revoked_event_lineage_v2,
    support_stream_ref_v2,
    support_transition_id_v2,
)
from pheroos.governance._support_v2.support_evidence_contracts import (
    SUPPORT_OBSERVATION_SCHEMA_V2,
    SUPPORT_PROPOSAL_SCHEMA_V2,
)
from pheroos.governance._support_v2.support_lease_contracts import (
    SUPPORT_EQUIVOCATION_SCHEMA_V2,
    SUPPORT_LEASE_SCHEMA_V2,
    SUPPORT_REVOCATION_SCHEMA_V2,
)
from pheroos.governance._support_v2.support_operations import (
    VerifiedSupportStateV2,
    advance_support_state_v2,
    open_support_authority_session_v2,
    rehydrate_support_state_v2,
    require_current_support_state_v2,
    support_state_is_current_v2,
)
from pheroos.governance._support_v2.support_source import (
    VerifiedSupportSourceV2,
    prepare_support_initialize_v2,
    prepare_support_issue_v2,
    prepare_support_revoke_v2,
    prepare_support_switch_v2,
    verify_support_request_source_v2,
)
from pheroos.governance._support_v2.support_stream_contracts import (
    MAX_SUPPORT_EVICTIONS_V2,
    support_switch_lineage_v2,
)
from pheroos.governance._support_v2.support_verification import (
    active_support_lease_from_parent_v2,
    project_support_lease_v2,
    project_support_revocation_v2,
)


_PUBLIC_MODULE = __name__
_NATIVE_PUBLIC_OBJECTS = (
    DurableSupportContextV2,
    MembershipClusterV2,
    MembershipCommitRequestV2,
    MembershipPrincipalV2,
    MembershipSnapshotV2,
    PrincipalVerificationRecordV2,
    PrincipalVerificationSetAdvanceRequestV2,
    PrincipalVerificationSetSnapshotV2,
    SupportAdvanceRequestV2,
    SupportEquivocationV2,
    SupportEvaluationV2,
    SupportLeaseProposalV2,
    SupportLeaseStatusV2,
    SupportLeaseV2,
    SupportMutationKindV2,
    SupportObservationV2,
    SupportRevocationV2,
    SupportSnapshotV2,
    VerifiedMembershipSourceV2,
    VerifiedMembershipStateV2,
    VerifiedPrincipalVerificationSourceV2,
    VerifiedPrincipalVerificationSetStateV2,
    VerifiedSupportSourceV2,
    VerifiedSupportStateV2,
    active_support_lease_from_parent_v2,
    advance_principal_verification_set_v2,
    advance_support_state_v2,
    canonical_membership_clusters_v2,
    canonical_support_leases_v2,
    canonical_support_observations_v2,
    canonical_verification_records_v2,
    commit_membership_epoch_v2,
    durable_support_context_v2,
    evaluate_support_v2,
    membership_projection_root_v2,
    membership_state_is_current_v2,
    membership_stream_ref_v2,
    membership_transition_id_v2,
    open_membership_authority_session_v2,
    open_principal_verification_authority_session_v2,
    open_support_authority_session_v2,
    prepare_membership_commit_v2,
    prepare_principal_verification_set_v2,
    prepare_support_initialize_v2,
    prepare_support_issue_v2,
    prepare_support_revoke_v2,
    prepare_support_switch_v2,
    principal_verification_set_is_current_v2,
    principal_verification_stream_ref_v2,
    principal_verification_transition_id_v2,
    project_support_lease_v2,
    project_support_revocation_v2,
    rehydrate_membership_state_v2,
    rehydrate_principal_verification_set_state_v2,
    rehydrate_support_state_v2,
    replacement_matches_prior_v2,
    require_current_membership_state_v2,
    require_current_principal_verification_set_v2,
    require_current_support_state_v2,
    revocation_matches_lease_v2,
    support_event_lineage_v2,
    support_history_advance_v2,
    support_issued_event_lineage_v2,
    support_lease_ref_v2,
    support_lease_status_v2,
    support_mutation_delta_root_v2,
    support_revocation_ref_v2,
    support_revoked_event_lineage_v2,
    support_state_is_current_v2,
    support_stream_ref_v2,
    support_switch_lineage_v2,
    support_transition_id_v2,
    verify_membership_request_source_v2,
    verify_principal_verification_source_v2,
    verify_support_request_source_v2,
)
for _public_object in _NATIVE_PUBLIC_OBJECTS:
    _public_object.__module__ = _PUBLIC_MODULE
del _public_object


__all__ = [
    "MAX_MEMBERSHIP_CLUSTERS_V2",
    "MAX_MEMBERSHIP_PRINCIPALS_V2",
    "MAX_MEMBERSHIP_SNAPSHOT_BYTES_V2",
    "MAX_PRINCIPAL_VERIFICATIONS_V2",
    "MAX_PRINCIPAL_VERIFICATION_SET_BYTES_V2",
    "MAX_SUPPORT_LEASES_V2",
    "MAX_SUPPORT_OBSERVATIONS_V2",
    "MAX_SUPPORT_REASON_CODES_V2",
    "MAX_SUPPORT_EVICTIONS_V2",
    "MAX_SUPPORT_RESOURCE_DEPTH_V2",
    "MAX_SUPPORT_RESOURCE_NODES_V2",
    "MAX_SUPPORT_RESOURCE_TEXT_BYTES_V2",
    "MAX_SUPPORT_SNAPSHOT_BYTES_V2",
    "MAX_SUPPORT_TEXT_BYTES_V2",
    "MAX_SUPPORT_TRACE_ROOTS_V2",
    "MAX_VERIFICATION_EVIDENCE_ROOTS_V2",
    "MAX_VERIFICATION_SOURCE_TRACE_ROOTS_V2",
    "MEMBERSHIP_CLUSTER_SCHEMA_V2",
    "MEMBERSHIP_COMMIT_REQUEST_SCHEMA_V2",
    "MEMBERSHIP_GENESIS_SNAPSHOT_ROOT_V2",
    "MEMBERSHIP_GENESIS_TRANSITION_ID_V2",
    "MEMBERSHIP_POLICY_VERSION_V2",
    "MEMBERSHIP_PRINCIPAL_SCHEMA_V2",
    "MEMBERSHIP_SNAPSHOT_SCHEMA_V2",
    "MEMBERSHIP_STATE_SCHEMA_V2",
    "PRINCIPAL_VERIFICATION_GENESIS_SNAPSHOT_ROOT_V2",
    "PRINCIPAL_VERIFICATION_GENESIS_TRANSITION_ID_V2",
    "PRINCIPAL_VERIFICATION_POLICY_VERSION_V2",
    "PRINCIPAL_VERIFICATION_RECORD_SCHEMA_V2",
    "PRINCIPAL_VERIFICATION_SET_REQUEST_SCHEMA_V2",
    "PRINCIPAL_VERIFICATION_SET_SNAPSHOT_SCHEMA_V2",
    "PRINCIPAL_VERIFICATION_SET_STATE_SCHEMA_V2",
    "SUPPORT_ADVANCE_REQUEST_SCHEMA_V2",
    "SUPPORT_EQUIVOCATION_SCHEMA_V2",
    "SUPPORT_EVALUATION_SCHEMA_V2",
    "SUPPORT_GENESIS_HISTORY_ROOT_V2",
    "SUPPORT_GENESIS_SNAPSHOT_ROOT_V2",
    "SUPPORT_GENESIS_TRANSITION_ID_V2",
    "SUPPORT_LEASE_SCHEMA_V2",
    "SUPPORT_OBSERVATION_SCHEMA_V2",
    "SUPPORT_PROPOSAL_SCHEMA_V2",
    "SUPPORT_REVOCATION_SCHEMA_V2",
    "SUPPORT_SNAPSHOT_SCHEMA_V2",
    "SUPPORT_STATE_SCHEMA_V2",
    "DurableSupportContextV2",
    "MembershipClusterV2",
    "MembershipCommitRequestV2",
    "MembershipPrincipalV2",
    "MembershipSnapshotV2",
    "PrincipalVerificationRecordV2",
    "PrincipalVerificationSetAdvanceRequestV2",
    "PrincipalVerificationSetSnapshotV2",
    "SupportAdvanceRequestV2",
    "SupportEquivocationV2",
    "SupportEvaluationV2",
    "SupportLeaseProposalV2",
    "SupportLeaseStatusV2",
    "SupportLeaseV2",
    "SupportMutationKindV2",
    "SupportObservationV2",
    "SupportRevocationV2",
    "SupportSnapshotV2",
    "VerifiedMembershipSourceV2",
    "VerifiedMembershipStateV2",
    "VerifiedPrincipalVerificationSourceV2",
    "VerifiedPrincipalVerificationSetStateV2",
    "VerifiedSupportSourceV2",
    "VerifiedSupportStateV2",
    "active_support_lease_from_parent_v2",
    "advance_principal_verification_set_v2",
    "advance_support_state_v2",
    "canonical_membership_clusters_v2",
    "canonical_support_leases_v2",
    "canonical_support_observations_v2",
    "canonical_verification_records_v2",
    "commit_membership_epoch_v2",
    "durable_support_context_v2",
    "evaluate_support_v2",
    "membership_projection_root_v2",
    "membership_state_is_current_v2",
    "membership_stream_ref_v2",
    "membership_transition_id_v2",
    "open_membership_authority_session_v2",
    "open_principal_verification_authority_session_v2",
    "open_support_authority_session_v2",
    "prepare_membership_commit_v2",
    "prepare_principal_verification_set_v2",
    "prepare_support_initialize_v2",
    "prepare_support_issue_v2",
    "prepare_support_revoke_v2",
    "prepare_support_switch_v2",
    "principal_verification_set_is_current_v2",
    "principal_verification_stream_ref_v2",
    "principal_verification_transition_id_v2",
    "project_support_lease_v2",
    "project_support_revocation_v2",
    "rehydrate_membership_state_v2",
    "rehydrate_principal_verification_set_state_v2",
    "rehydrate_support_state_v2",
    "replacement_matches_prior_v2",
    "require_current_membership_state_v2",
    "require_current_principal_verification_set_v2",
    "require_current_support_state_v2",
    "revocation_matches_lease_v2",
    "support_event_lineage_v2",
    "support_history_advance_v2",
    "support_issued_event_lineage_v2",
    "support_lease_ref_v2",
    "support_lease_status_v2",
    "support_mutation_delta_root_v2",
    "support_revocation_ref_v2",
    "support_revoked_event_lineage_v2",
    "support_state_is_current_v2",
    "support_stream_ref_v2",
    "support_switch_lineage_v2",
    "support_transition_id_v2",
    "verify_membership_request_source_v2",
    "verify_principal_verification_source_v2",
    "verify_support_request_source_v2",
]
